export const collaborationZh = {
 title: '协作伙伴', intro: '选择此 AI 员工可以请求协助的飞书伙伴，无需拥有对方的管理权限。', platform: '协作伙伴目前仅支持飞书 AI 员工。', noAccess: '仅此 AI 员工的管理者可以查看和配置协作伙伴。',
 add: '添加伙伴', empty: '尚未配置协作伙伴，添加后即可在群聊中请求协助。', direction: '{source} 请求 {target} 协助', peer: '选择伙伴', save: '保存', saved: '协作伙伴已保存并启用', enable: '启用协作', pause: '暂停协作', remove: '移除伙伴', retry: '重试', close: '关闭', cancel: '取消', loading: '正在加载…', search: '按名称或描述搜索飞书伙伴', noPeers: '没有匹配的飞书伙伴，请尝试其他关键词', alreadyAdded: '已添加',
 usageHint: '保存后即可向伙伴请求协助。实际协作会在当前群进行，并检查发起人的双方使用权限及群内可用情况；失败后不会反复请求。暂不可用的伙伴也可以先保存。', unavailable: '暂不可用，可先保存', pauseConfirm: '暂停后将停止新协作，并可能中止正在进行的协作（{count} 项）。是否继续？', removeConfirm: '移除后将停止此伙伴的协作，并取消进行中的协作（{count} 项）。历史记录会保留。是否继续？', discard: '关闭后将放弃尚未保存的选择，是否继续？', active: '进行中：{count}', confirm: '确认',
 reasons: { employee_unavailable: 'AI 员工暂不可用，恢复后即可请求协助。', runtime_unavailable: '运行节点暂不可用，恢复后即可请求协助。', credentials_changed: '飞书应用配置已变更，将在实际请求时检查可用情况。', permission_revoked: '此前验证所依赖的协作配置或权限已撤回。请重新启用伙伴，并从双方都在的群聊发起协作。', verification_cancelled: '此前的群通道验证已取消。请从双方都在的群聊重新发起协作。', probe_delivery_failed: '群验证消息发送失败。请确认两个飞书应用都在同一群中，再从群聊发起一次协作以重新验证。', verification_expired: '群通道验证已过期。请从双方都在的群聊重新发起一次协作。', probe_identity_mismatch: '群验证返回的机器人身份不匹配。请检查双方飞书应用配置后重试。', invalid_setup_probe: '群通道验证结果无效。请检查双方飞书应用配置后重试。' },
 status: { ready: '群通道已验证', verified: '群通道已验证', runtime_ready: '运行时就绪，群通道未验证', unavailable: '暂不可用', enabled: '已启用', paused: '已暂停' },
}
export const collaborationEn = {
 title: 'Collaboration partners', intro: 'Choose Feishu partners this AI employee can ask for help. You do not need to manage the partner.', platform: 'Collaboration partners currently support Feishu employees only.', noAccess: 'Only managers of this employee can view and configure partners.',
 add: 'Add partner', empty: 'No partners yet. Add one to request help in group chats.', direction: '{source} asks {target} for help', peer: 'Choose partner', save: 'Save', saved: 'Partner saved and enabled', enable: 'Enable collaboration', pause: 'Pause collaboration', remove: 'Remove partner', retry: 'Retry', close: 'Close', cancel: 'Cancel', loading: 'Loading…', search: 'Search Feishu partners by name or description', noPeers: 'No matching Feishu partners. Try another search.', alreadyAdded: 'Already added',
 usageHint: 'Once saved, this employee can ask the partner for help in the current group. Each request checks the initiating user’s permission to use both employees and availability in the group. Failed requests will not be repeated. You can also save unavailable partners.', unavailable: 'Unavailable; can still be saved', pauseConfirm: 'Pausing stops new collaboration and may interrupt active work ({count}). Continue?', removeConfirm: 'Removing this partner stops collaboration and cancels active work ({count}). History is retained. Continue?', discard: 'Discard your unsaved selection and close?', active: 'Active: {count}', confirm: 'Confirm',
 reasons: { employee_unavailable: 'An employee is unavailable. Requests can resume when it is restored.', runtime_unavailable: 'A runtime is unavailable. Requests can resume when it is restored.', credentials_changed: 'Feishu app settings changed. Availability will be checked when help is requested.', permission_revoked: 'The collaboration configuration or permission used by the earlier verification was revoked. Enable the partner again, then start collaboration from a group containing both apps.', verification_cancelled: 'The earlier group transport verification was cancelled. Start collaboration again from a group containing both apps.', probe_delivery_failed: 'The group verification message could not be delivered. Ensure both Feishu apps are in the same group, then start collaboration there to verify again.', verification_expired: 'Group transport verification expired. Start collaboration again from a group containing both apps.', probe_identity_mismatch: 'Group verification returned mismatched bot identities. Check both Feishu app configurations and retry.', invalid_setup_probe: 'The group transport verification result was invalid. Check both Feishu app configurations and retry.' },
 status: { ready: 'Group transport verified', verified: 'Group transport verified', runtime_ready: 'Runtime ready; group transport unverified', unavailable: 'Unavailable', enabled: 'Enabled', paused: 'Paused' },
}
export const collaborationJa = {
 title: '協力パートナー', intro: 'この AI 社員が協力を依頼できる Feishu パートナーを選択します。相手の管理権限は不要です。', platform: '協力パートナーは現在 Feishu の AI 社員のみ対応しています。', noAccess: 'この AI 社員の管理者のみがパートナーを表示・設定できます。',
 add: 'パートナーを追加', empty: 'パートナーはまだありません。追加するとグループ内で協力を依頼できます。', direction: '{source} が {target} に協力を依頼', peer: 'パートナーを選択', save: '保存', saved: 'パートナーを保存し、有効にしました', enable: '協力を有効化', pause: '協力を一時停止', remove: 'パートナーを削除', retry: '再試行', close: '閉じる', cancel: 'キャンセル', loading: '読み込み中…', search: '名前または説明で Feishu パートナーを検索', noPeers: '一致する Feishu パートナーがありません。別の語句で検索してください。', alreadyAdded: '追加済み',
 usageHint: '保存後、現在のグループでパートナーに協力を依頼できます。依頼時に、依頼者の双方の利用権限とグループ内での利用可否を確認します。失敗した依頼を繰り返し送ることはありません。利用できないパートナーも先に保存できます。', unavailable: '利用不可・保存可能', pauseConfirm: '新しい協力を停止し、進行中の協力（{count} 件）を中断する場合があります。続けますか？', removeConfirm: '協力を停止し、進行中の協力（{count} 件）をキャンセルします。履歴は保持されます。続けますか？', discard: '未保存の選択を破棄して閉じますか？', active: '進行中：{count} 件', confirm: '確認',
 reasons: { employee_unavailable: 'AI 社員を利用できません。復旧後に協力を依頼できます。', runtime_unavailable: '実行ノードを利用できません。復旧後に協力を依頼できます。', credentials_changed: 'Feishu アプリ設定が変更されました。依頼時に利用可否を確認します。', permission_revoked: '以前の検証で使われた協力設定または権限が取り消されました。パートナーを再度有効にし、両方のアプリがいるグループから協力を開始してください。', verification_cancelled: '以前のグループ経路検証はキャンセルされました。両方のアプリがいるグループから協力を再度開始してください。', probe_delivery_failed: 'グループ検証メッセージを送信できませんでした。両方の Feishu アプリが同じグループにいることを確認し、そのグループから協力を再度開始してください。', verification_expired: 'グループ経路の検証期限が切れました。両方のアプリがいるグループから協力を再度開始してください。', probe_identity_mismatch: 'グループ検証でボット ID が一致しませんでした。両方の Feishu アプリ設定を確認してください。', invalid_setup_probe: 'グループ経路の検証結果が無効です。両方の Feishu アプリ設定を確認してください。' },
 status: { ready: 'グループ経路を検証済み', verified: 'グループ経路を検証済み', runtime_ready: 'ランタイム準備済み・グループ経路未検証', unavailable: '利用不可', enabled: '有効', paused: '一時停止' },
}
