export const collaborationZh = {
 steps: { peer: '选伙伴', group: '选群', verify: '验证' }, groupPlaceholder: '请选择共同群', noGroupOptions: '没有可选的共同群', noGroupMatch: '没有匹配的群',
 reasons: {"verification_cancelled": "验证已取消。请重新验证连接。", "employee_unavailable": "AI 员工不可用。请先启用双方 AI 员工。", "credentials_changed": "飞书应用凭证已变更。请重新验证连接。", "permission_revoked": "管理权限已变更。请联系管理员恢复双方管理权限。", "runtime_unavailable": "运行节点不可用。请先恢复双方运行节点。", "stale_setup_probe": "验证配置已变更。请重新验证连接。", "invalid_setup_probe": "验证消息无效。请重新验证连接。", "probe_delivery_failed": "测试消息发送失败。请检查飞书应用权限和群成员后重试。", "probe_identity_mismatch": "收到的测试消息与应用身份不符。请检查双方飞书应用配置后重试。", "verification_expired": "验证已过期。请重新验证连接。"},
 title: '协作伙伴', intro: '配置此 AI 员工可以请求协助的伙伴。只有同时有权使用双方的用户才能发起协作。', platform: '协作伙伴目前仅支持飞书 AI 员工。', noAccess: '仅此 AI 员工的管理者可以查看和配置协作伙伴。', add: '添加伙伴', empty: '尚未配置协作伙伴', direction: '{source} 请求 {target} 协助', peer: '选择伙伴', group: '选择共同飞书群', verify: '验证连接', enable: '启用协作', pause: '暂停协作', remove: '移除伙伴', retry: '重试', close: '关闭', cancel: '取消', loading: '正在加载…', search: '按名称或描述搜索', noPeers: '没有可管理的飞书伙伴', noGroups: '未找到共同群。请先将双方飞书应用加入同一群后重试。', warning: '验证会在所选群发送两条测试消息，不会触发 AI 任务。验证成功后仍需手动启用协作。', waiting: '正在等待双方收到测试消息，可关闭后稍后查看。', ready: '双向连接已验证，可以启用协作。', unavailable: '伙伴已停用或没有可用运行节点', pauseConfirm: '暂停后将停止新协作，并可能中止正在进行的协作（{count} 项）。是否继续？', removeConfirm: '移除后将停止此伙伴的协作，并取消进行中的协作（{count} 项）。历史记录会保留。是否继续？', discard: '关闭后将放弃尚未提交的选择，是否继续？', failed: '连接验证未完成。请检查双方群成员和事件接收配置后重试。', expired: '验证已过期，请重新验证连接。', active: '进行中：{count}', confirm: '确认', status: { pending: '验证中', ready: '已验证', failed: '验证失败', expired: '验证过期', unavailable: '暂不可用', enabled: '已启用', paused: '已暂停' },
}
export const collaborationEn = {
 steps: { peer: 'Partner', group: 'Group', verify: 'Verify' }, groupPlaceholder: 'Choose a shared group', noGroupOptions: 'No shared groups available', noGroupMatch: 'No matching groups',
 reasons: {"verification_cancelled": "Verification was cancelled. Verify the connection again.", "employee_unavailable": "An employee is unavailable. Enable both AI employees first.", "credentials_changed": "Feishu app credentials changed. Verify the connection again.", "permission_revoked": "Management permissions changed. Ask an administrator to restore access to both employees.", "runtime_unavailable": "A runtime is unavailable. Restore both runtimes first.", "stale_setup_probe": "Verification settings changed. Verify the connection again.", "invalid_setup_probe": "The verification message was invalid. Verify the connection again.", "probe_delivery_failed": "Test messages could not be sent. Check Feishu app permissions and group membership, then retry.", "probe_identity_mismatch": "The test message identity did not match the app. Check both Feishu app configurations, then retry.", "verification_expired": "Verification expired. Verify the connection again."},
 title: 'Collaboration partners', intro: 'Choose whom this AI employee can ask for help. Users must have permission to use both employees to start a collaboration.', platform: 'Collaboration partners currently support Feishu employees only.', noAccess: 'Only managers of this employee can view and configure partners.', add: 'Add partner', empty: 'No collaboration partners yet', direction: '{source} asks {target} for help', peer: 'Choose partner', group: 'Choose shared Feishu group', verify: 'Verify connection', enable: 'Enable collaboration', pause: 'Pause collaboration', remove: 'Remove partner', retry: 'Retry', close: 'Close', cancel: 'Cancel', loading: 'Loading…', search: 'Search by name or description', noPeers: 'No manageable Feishu partners', noGroups: 'No shared groups found. Add both Feishu apps to the same group, then retry.', warning: 'Verification sends two test messages to the selected group without starting AI tasks. Enable collaboration manually after verification succeeds.', waiting: 'Waiting for both test messages to arrive. You can close this panel and check later.', ready: 'Both directions verified. You can enable collaboration.', unavailable: 'Partner is disabled or has no available runtime', pauseConfirm: 'Pausing stops new collaboration and may interrupt active work ({count}). Continue?', removeConfirm: 'Removing this partner stops collaboration and cancels active work ({count}). History is retained. Continue?', discard: 'Discard your unsubmitted selections and close?', failed: 'Connection verification did not complete. Check group membership and event reception for both apps, then retry.', expired: 'Verification expired. Verify the connection again.', active: 'Active: {count}', confirm: 'Confirm', status: { pending: 'Verifying', ready: 'Verified', failed: 'Verification failed', expired: 'Verification expired', unavailable: 'Unavailable', enabled: 'Enabled', paused: 'Paused' },
}
export const collaborationJa = {
 steps: { peer: '相手', group: 'グループ', verify: '検証' }, groupPlaceholder: '共通グループを選択', noGroupOptions: '選択できる共通グループがありません', noGroupMatch: '一致するグループがありません',
 reasons: {"verification_cancelled": "検証がキャンセルされました。接続を再度検証してください。", "employee_unavailable": "AI 社員を利用できません。双方の AI 社員を有効にしてください。", "credentials_changed": "Feishu アプリの認証情報が変更されました。接続を再度検証してください。", "permission_revoked": "管理権限が変更されました。管理者に双方の管理権限の復元を依頼してください。", "runtime_unavailable": "実行ノードを利用できません。双方の実行ノードを復旧してください。", "stale_setup_probe": "検証設定が変更されました。接続を再度検証してください。", "invalid_setup_probe": "検証メッセージが無効です。接続を再度検証してください。", "probe_delivery_failed": "テストメッセージを送信できませんでした。Feishu アプリの権限とグループ参加を確認して再試行してください。", "probe_identity_mismatch": "テストメッセージの送信者がアプリと一致しません。双方の Feishu アプリ設定を確認して再試行してください。", "verification_expired": "検証の有効期限が切れました。接続を再度検証してください。"},
 title: '協力パートナー', intro: 'この AI 社員が協力を依頼できる相手を設定します。依頼するユーザーには双方の利用権限が必要です。', platform: '協力パートナーは現在 Feishu の AI 社員のみ対応しています。', noAccess: 'この AI 社員の管理者のみがパートナーを表示・設定できます。', add: 'パートナーを追加', empty: '協力パートナーはまだありません', direction: '{source} が {target} に協力を依頼', peer: 'パートナーを選択', group: '共通の Feishu グループを選択', verify: '接続を検証', enable: '協力を有効化', pause: '協力を一時停止', remove: 'パートナーを削除', retry: '再試行', close: '閉じる', cancel: 'キャンセル', loading: '読み込み中…', search: '名前または説明で検索', noPeers: '管理可能な Feishu パートナーがありません', noGroups: '共通グループがありません。両方の Feishu アプリを同じグループに追加して再試行してください。', warning: '検証では選択したグループにテストメッセージを 2 件送信します。AI タスクは実行しません。成功後、手動で協力を有効にしてください。', waiting: '双方のテストメッセージの受信を待っています。閉じて後から確認できます。', ready: '双方向の接続を確認しました。協力を有効にできます。', unavailable: 'パートナーが無効か、利用可能な実行ノードがありません', pauseConfirm: '新しい協力を停止し、進行中の協力（{count} 件）を中断する場合があります。続けますか？', removeConfirm: '協力を停止し、進行中の協力（{count} 件）をキャンセルします。履歴は保持されます。続けますか？', discard: '未送信の選択を破棄して閉じますか？', failed: '接続の検証が完了しませんでした。双方のグループ参加とイベント受信設定を確認して再試行してください。', expired: '検証の有効期限が切れました。再度検証してください。', active: '進行中：{count} 件', confirm: '確認', status: { pending: '検証中', ready: '検証済み', failed: '検証失敗', expired: '期限切れ', unavailable: '利用不可', enabled: '有効', paused: '一時停止' },
}
